export const interfaceTxt = {
    en: {
        detailedCard: {
            attacksPerf: "How many attacks has this character performed?",
            checkBoxYes: "Yes(average chance)",
            checkBoxFailed: "Failed chance",
            checkBoxGuaran: "Guaranteed Chance",
            level: "Level",
            kiSpheres: "Has this character obtained 5 or more ki spheres?",
            kiSpheresTip: "(chance for additional attack)",
            gokuVegetaEnemy: 'Is there a "Goku\'s family" or "Vegeta\'s family" enemy?',
            saiyanRace: "Saiyan Warrior Race",
            superSaiyanRace: "Super Saiyan",
            gt: "GT",
            shattering: "Shattering the Limit",
            saiyanLin: "The Sayiyan Lineage",
            shockSpeed: "Shocking Speed",
            legPower: "Legenday Power",
            ovLeaATK: "Overall leader ATK",
            ovLeaDEF: "Overall leader DEF",
            atkSupp: "ATK Support",
            defSupp: "DEF Support",
            atkBefSAtk: "ATK before super attacking",
            atkAftSAtk: "ATK after super attacking",
            defBefSAtk: "DEF before super attacking",
            defAftSAtk: "DEF after super attacking",
            damageFromAtk: "Damage taken from an attack of",
        },
    },
};
